"""
Historonics Agent Schema - Structured Hypothesis Outputs.

Defines Pydantic models for historical analysis and hypothesis generation.
All outputs are advisory only - never executable logic.
"""
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum


class HypothesisType(str, Enum):
    """Types of hypotheses generated by Historonics Agent."""
    HISTORICAL_ANALOGY = "historical_analogy"
    REGIME_TRANSITION = "regime_transition"
    FAILURE_PRECURSOR = "failure_precursor"
    PARAMETER_RISK = "parameter_risk"


class HistoricalAnalog(BaseModel):
    """A historical period that may be analogous to current conditions."""
    period: str = Field(..., description="Time period identifier (e.g., 'Q4 2018', '2020 Q1-Q2')")
    description: str = Field(..., description="Why this period is relevant")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in analog relevance (0.0 = low, 1.0 = high)")


class Hypothesis(BaseModel):
    """
    A structured hypothesis generated by the Historonics Agent.
    
    All hypotheses are UNTESTED and ADVISORY ONLY.
    They suggest what to study next, never how to compute results.
    """
    hypothesis_id: str = Field(..., description="Stable hash identifier for this hypothesis")
    hypothesis_type: HypothesisType = Field(..., description="Type of hypothesis")
    summary: str = Field(..., description="Concise statement of the hypothesis")
    historical_analogs: List[HistoricalAnalog] = Field(default_factory=list, description="Relevant historical periods")
    linked_insights: List[str] = Field(default_factory=list, description="Insight IDs that inform this hypothesis")
    regimes_implicated: List[str] = Field(default_factory=list, description="Regime IDs relevant to this hypothesis")
    uncertainty_notes: str = Field(..., description="Explicit limitations and unknowns")
    recommended_validation: str = Field(..., description="How this could be tested (non-numeric, non-binding)")
    
    # Metadata
    generated_at: datetime = Field(default_factory=datetime.now, description="When this hypothesis was generated")
    source: str = Field(default="Historonics Agent", description="Source of hypothesis")
    status: str = Field(default="UNTESTED", description="Status: UNTESTED (advisory only)")
    evidence_level: str = Field(default="Narrative only", description="Evidence level: Narrative only (not validated)")


class HistoronicsOutput(BaseModel):
    """Complete output from Historonics Agent."""
    hypotheses: List[Hypothesis] = Field(default_factory=list, description="Generated hypotheses")
    generated_at: datetime = Field(default_factory=datetime.now)
    report_id: Optional[str] = Field(default=None, description="Report ID that triggered this analysis")
    iteration_id: Optional[str] = Field(default=None, description="Research loop iteration ID")

